# Site settings
title: MLB Showdown Card Data
tag_text: MLB Showdown Card Data
description: MLB Showdown card modeling, simulation, and data visualization.

# Build settings
markdown: kramdown

exclude: ["README.md"]
exclude: [node_modules]
